// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var VsCode = require("./VsCode.bs.js");
var Environment = require("./Environment.bs.js");
var VscodeLanguageclient = require("vscode-languageclient");

function activate(context) {
  return VsCode.MultiWorkspace.start(context, /* array */[], (function ($$document, folder) {
                var match = Environment.serverOptionsForFolder($$document, folder);
                if (match !== undefined) {
                  return new VscodeLanguageclient.LanguageClient("vscode-reason", "Reason/OCaml Language Server Client for VSCode", match, undefined);
                }
                
              }));
}

exports.activate = activate;
/* VsCode Not a pure module */
